### ISSUE TITLE
error on louvain clustering

### ISSUE THREAD

**Issue by anupparikh** [biolab/orange3-single-cell#94] opened 2018-02-13 21:43 UTC
##### Single Cell version
0.2.3

##### Orange version
3.9.1

Just connected the cluster widget to dataset output. 

![screen shot 2018-02-13 at 1 41 16 pm](https://user-images.githubusercontent.com/111604/36175235-9f1e373e-10c3-11e8-8fe4-af846ff93383.png)

Exception: | AttributeError: 'Outputs' object has no attribute 'graph'
-- | --
Module: | orangecontrib.single_cell.widgets.owlouvainclustering:336
Widget Name: | Louvain Clustering
Widget Module: | orangecontrib.single_cell.widgets.owlouvainclustering:336
Widget Scheme: | /var/folders/jy/58rfl2zn0733y5jns_zmptb40000gn/T/ows-q8w8jnj_.ows.xml
Version: | 3.9.1
Environment: | Python 3.6.1 on Darwin 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
Installed Packages: | AnyQt==0.0.8, Bottleneck==1.2.0, CommonMark==0.7.3, Orange3-SingleCell==0.2.3, Orange3==3.9.1, PyQt5==5.9, certifi==2018.1.18, chardet==3.0.4, decorator==4.2.1, dill==0.2.6, docutils==0.13.1, future==0.16.0, idna==2.6, joblib==0.11, keyring==10.3.1, keyrings.alt==2.2, networkx==2.1, numpy==1.12.1, pip==9.0.1, pyqtgraph==0.10.0, requests==2.18.4, scikit-learn==0.18.2, scipy==0.19.1, serverfiles==0.2.1, setuptools==38.5.1, sip==4.19.3, six==1.10.0, urllib3==1.22, wheel==0.30.0, xlrd==1.0.0
Machine ID: | 154505285572042
Stack Trace: | Traceback (most recent call last):  File "/Applications/scOrange 2.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/canvas/scheme/widgetsscheme.py", line 832, in process_signals_for_widget    handler(*args)  File "/Applications/scOrange 2.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orangecontrib/single_cell/widgets/owlouvainclustering.py", line 336, in set_data    self.Outputs.graph.send(None)AttributeError: 'Outputs' object has no attribute 'graph'
Local Variables: | OrderedDict([('data',              [[0.000, 0.000, 5.648, 5.267, 0.000, ... \| healthy] {1, 6681b0788fc2b2e21975e26f588cc7a9, ACGGGAGATGACCA-1}, [0.983, 0.573, 0.000, 0.000, 0.000, ... \| AML] {1, 7c1e27874a82e7d5c1c877fa2cba7ba7, GAACAGCTGCTTAG-1}, [0.000, 0.000, 0.000, 0.000, 4.069, ... \| healthy] {2, b9d78fbc8b1bf9aa478e1fbd93ac883c, TCTTACGAAAAAGC-1}, [0.000, 0.000, 0.000, 0.000, 2.304, ... \| healthy] {1, 841c0e79f017a8ece40b2532f82a9c7a, CGAGCCGACTCTAT-1}, [0.000, 0.000, 0.000, 0.000, 0.000, ... \| healthy] {2, 08c51bbdc6bb95fc17cd3965e6d6c4fb, GCAAACTGTTGGCA-1}, ...]),             ('self',              <orangecontrib.single_cell.widgets.owlouvainclustering.OWLouvainClustering object at 0x13678ef78>)])

**Comment by BlazZupan** [comment] 2018-03-16 14:54
As we cannot reproduce this issue anymore, we assume it was fixed in #83, else, please reopen.

**Closed by BlazZupan** 2018-03-16 14:54 UTC
